-- Seeds: password = "123456"
-- Hash generated by: bcrypt::hash("123456", bcrypt::DEFAULT_COST)
INSERT INTO auth_users (id, phone, password_hash, nickname, avatar_url) VALUES
(1, '13800000001', '$2b$12$bRl2KGQSEHwGZzCVbHyOBudrvl3xPcPyF9KlEGh5ptCNWE7SqEkGi', 'Alice', 'https://api.dicebear.com/7.x/identicon/png?seed=alice'),
(2, '13800000002', '$2b$12$bRl2KGQSEHwGZzCVbHyOBudrvl3xPcPyF9KlEGh5ptCNWE7SqEkGi', 'Bob',   'https://api.dicebear.com/7.x/identicon/png?seed=bob'),
(3, '13800000003', '$2b$12$bRl2KGQSEHwGZzCVbHyOBudrvl3xPcPyF9KlEGh5ptCNWE7SqEkGi', 'Carol', 'https://api.dicebear.com/7.x/identicon/png?seed=carol')
ON CONFLICT (id) DO NOTHING;

-- Sync sequence after manual id insertion
SELECT setval('auth_users_id_seq', COALESCE((SELECT MAX(id) FROM auth_users), 0));
